name: stridelog
description: "Desfrute de uma jornada saud√°vel com nosso app de monitoramento fitness"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  crypto: ^3.0.0
  sqflite: 2.3.3+1
  path: ^1.8.3
  path_provider: ^2.1.2
  provider: ^6.1.2
  http: ^1.2.0
  geolocator: ^10.1.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path:
  remove_alpha_ios: true